In [ ]:
import pandas as pd

# Specify the correct encoding when reading the CSV file
data = pd.read_excel('/content/June.xlsx')

# Display the DataFrame
print(data)

       Order ID  Item ID  Flavour ID Product Gift  Product Category  \
0        460859     6637       13646          NaN  Wireless Earbuds
1        460860     6645       13658          NaN     Smart Watches
2        460861     4504       10684          NaN           Mobiles
3        460862     6209       12880          NaN  Wireless Earbuds
4        460864     6630       13630          NaN     Smart Watches
...         ...      ...         ...          ...               ...
28813    491148     6679       13723          NaN           Mobiles
28814    491149     5709       11880          NaN           Mobiles
28815    491150     5934       13989          NaN           Mobiles
28816    491151     5261       11014          NaN  Wireless Earbuds
28817    491152     5099       10642          NaN           Mobiles

      Product Brand                    Product Title   Product Color  \
0              Dany                 Dany Airdots 101           black
1          Assorted      WearFit HK9 Pro Smart Watch           black
2            Xiaomi             Xiaomi Redmi Note 11   graphite_gray
3          Assorted       M90 Pro TWS Gaming Earbuds           black
4          Kieslect  Kieslect KS Smart Calling Watch   orange_yellow
...             ...                              ...             ...
28813       Infinix               Infinix Smart 7 HD       ink_black
28814       VGO-TEL                   VGO TEL NEW 20            blue
28815       Samsung              Samsung Galaxy A04e           black
28816       Infinix    Infinix XE20 Wireless Earbuds           white
28817          itel                     Itel Magic 3  gradation_blue

        Product Memory  Product Value  ...       Courier   Tracking ID  \
0                    0           2999  ...       leopard   KI763095177
1                    0           8149  ...       leopard   ID197537921
2      128gb - 6gb ram          68499  ...       leopard   ID197537469
3                    0           1349  ...  priceoye-khi       1000175
4                    0          16499  ...           NaN           NaN
...                ...            ...  ...           ...           ...
28813   64gb - 2gb ram          25999  ...           tcs  779408184801
28814   64gb - 4gb ram          24499  ...           tcs  779408183963
28815   64gb - 3gb ram          33099  ...           tcs  779408183927
28816                0           2799  ...           tcs  779408184802
28817         standard           5200  ...           NaN           NaN

                             Status         Status Date          Order Date  \
0                         delivered 2023-06-08 08:58:14 2023-06-01 00:00:44
1                          returned 2023-06-13 14:58:53 2023-06-01 00:01:30
2                         delivered 2023-06-03 14:58:15 2023-06-01 00:03:27
3                         delivered 2023-06-03 16:12:45 2023-06-01 00:04:38
4               cancelled_abandoned 2023-06-01 16:28:02 2023-06-01 00:05:27
...                             ...                 ...                 ...
28813                       transit 2023-07-05 15:17:51 2023-06-30 23:42:53
28814                     delivered 2023-07-07 09:18:31 2023-06-30 23:44:22
28815                     delivered 2023-07-07 12:17:00 2023-06-30 23:48:14
28816                     delivered 2023-07-07 15:16:40 2023-06-30 23:49:26
28817  cancelled_number_unreachable 2023-07-04 14:40:15 2023-06-30 23:54:25

       issued Coupon      Delivery Type  Direct Order Placed  \
0                  -  standard_shipping                   No
1                  -  standard_shipping                   No
2                  -  standard_shipping                   No
3                  -  standard_shipping                  Yes
4                  -  standard_shipping                   No
...              ...                ...                  ...
28813              -  standard_shipping                   No
28814              -  standard_shipping                   No
28815              -  standard_shipping                   No
28816              -  standard_shipping                   No
28817              -  standard_shipping                   No

       Expected Delivery Date                        Vendor Name
0                  2023-06-03                  Dany Technologies
1                  2023-06-05                             Addons
2                  2023-06-03                         SB Mobiles
3                  2023-06-04                       Azan Traders
4                  2023-06-05                                NaN
...                       ...                                ...
28813              2023-07-04                    Al Hamd Telecom
28814              2023-07-05          Friends Mobile System RWP
28815              2023-07-04  GNEXT SOLUTIONS (PRIVATE) LIMITED
28816              2023-07-04                   Siccotel Trading
28817              2023-07-04                                NaN

[28818 rows x 44 columns]

In [ ]:
duplicates = data[data['Phone'].duplicated()]

# Display the DataFrame with duplicate values in the 'Phone' column
print(duplicates)

       Order ID  Item ID  Flavour ID Product Gift  Product Category  \
6        460866     4015       11672          NaN           Mobiles
17       460881     4014       11734          NaN           Mobiles
22       460888     4999       10495          NaN           Mobiles
31       460897     6396       13569          NaN           Laptops
44       460910     3797        8089          NaN           Mobiles
...         ...      ...         ...          ...               ...
28795    491129     5936       13715          NaN           Mobiles
28799    491134     5742       14116          NaN           Mobiles
28804    491139     6679       13723          NaN           Mobiles
28812    491147     6453       13334          NaN     Smart Watches
28816    491151     5261       11014          NaN  Wireless Earbuds

      Product Brand                                      Product Title  \
6           Samsung                              Samsung Galaxy A33 5G
17          Samsung                                 Samsung Galaxy A73
22          Samsung                              Samsung Galaxy S21 FE
31           Lenovo  Lenovo Ideapad 3 1115G4 15.6 Inches 11th Gen C...
44          Samsung                                 Samsung Galaxy A32
...             ...                                                ...
28795       Samsung                                 Samsung Galaxy A14
28799     me Mobile                           me Mobile Magic Star Pro
28804       Infinix                                 Infinix Smart 7 HD
28812      Assorted                                   T500 Smart Watch
28816       Infinix                      Infinix XE20 Wireless Earbuds

       Product Color   Product Memory  Product Value  ...          Courier  \
6      awesome_white  128gb - 8gb ram          99999  ...              NaN
17     awesome_white  256gb - 8gb ram         164999  ...   selfpickup-lhe
22          lavender  128gb - 8gb ram         159999  ...              NaN
31     platinum_grey    1tb - 4gb ram         115499  ...              NaN
44     awesome_black  128gb - 6gb ram          79999  ...              NaN
...              ...              ...            ...  ...              ...
28795    light_green  128gb - 6gb ram          62399  ...              tcs
28799          black         standard           2599  ...              NaN
28804      ink_black   64gb - 2gb ram          25999  ...              NaN
28812          black                0           1499  ...  selfpickup-giga
28816          white                0           2799  ...              tcs

        Tracking ID                       Status         Status Date  \
6               NaN          cancelled_abandoned 2023-06-26 17:58:29
17              NaN     cancelled_not_interested 2023-06-01 10:19:20
22              NaN          cancelled_abandoned 2023-06-01 16:27:59
31              NaN          cancelled_abandoned 2023-06-01 16:54:49
44              NaN          cancelled_abandoned 2023-06-01 19:20:06
...             ...                          ...                 ...
28795  779408184800                      transit 2023-07-05 15:52:08
28799           NaN  cancelled_already_purchased 2023-07-05 18:35:29
28804           NaN          cancelled_abandoned 2023-07-08 16:38:39
28812       1000255                    delivered 2023-07-08 16:48:44
28816  779408184802                    delivered 2023-07-07 15:16:40

               Order Date  issued Coupon      Delivery Type  \
6     2023-06-01 00:06:37              -  standard_shipping
17    2023-06-01 00:14:08              -         selfpickup
22    2023-06-01 00:19:25              -         openparcel
31    2023-06-01 00:39:37              -  standard_shipping
44    2023-06-01 00:57:38              -         openparcel
...                   ...            ...                ...
28795 2023-06-30 22:47:06              -  standard_shipping
28799 2023-06-30 23:11:16              -  standard_shipping
28804 2023-06-30 23:24:18              -  standard_shipping
28812 2023-06-30 23:41:05              -         selfpickup
28816 2023-06-30 23:49:26              -  standard_shipping

       Direct Order Placed  Expected Delivery Date  \
6                       No              2023-06-03
17                      No              2023-06-04
22                      No              2023-06-03
31                      No              2023-06-04
44                      No              2023-06-03
...                    ...                     ...
28795                   No              2023-07-04
28799                   No              2023-07-04
28804                   No              2023-07-03
28812                   No              2023-07-03
28816                   No              2023-07-04

                       Vendor Name
6                              NaN
17                             NaN
22                             NaN
31                             NaN
44                             NaN
...                            ...
28795        M&P (Muller & Phipps)
28799                          NaN
28804                          NaN
28812  Standard Mobile Accessories
28816             Siccotel Trading

[6439 rows x 44 columns]

In [ ]:

# Find unique values in the 'Phone' column
unique_values = data['Phone'].unique()

# Create a new DataFrame from the unique values
df_unique = pd.DataFrame({'Phone': unique_values})

# Display the resulting DataFrame
print(df_unique)

              Phone
0      9.231393e+11
1      9.233600e+11
2      9.231034e+11
3      9.231727e+11
4      9.232140e+11
...             ...
22374  9.231606e+11
22375  9.230017e+11
22376  9.231300e+11
22377  9.230172e+11
22378  9.234273e+11

[22379 rows x 1 columns]

In [ ]:
# Merge the two DataFrames on the 'Phone' column
merged_df = pd.merge(duplicates, df_unique, on='Phone')

# Drop duplicates based on the 'Phone' column
unique_merged_df = merged_df.drop_duplicates(subset='Phone')

# Display the resulting DataFrame
print(unique_merged_df)
#print(sum(unique_merged_df['Phone']))

      Order ID  Item ID  Flavour ID  Product Gift  Product Category  \
0       331773     5878       12204           NaN     Smart Watches
7       331776     3933       10555           NaN           Mobiles
8       331779     4504       10683           NaN           Mobiles
9       331801     5775       12141           NaN           Mobiles
11      331816     4519        9625           NaN           Mobiles
...        ...      ...         ...           ...               ...
4463    358044     5203       10919           NaN     Smart Watches
4464    358045     5498       11644           NaN           Mobiles
4465    358050     6064       12527           NaN  Wireless Earbuds
4466    358054     5393       11237           NaN           Mobiles
4467    358056     5253       12452           NaN  Wireless Earbuds

     Product Brand                              Product Title   Product Color  \
0           Huawei                              Huawei Band 7           black
7             Vivo                                  Vivo V23e  sunshine_coast
8           Xiaomi                       Xiaomi Redmi Note 11   twilight_blue
9            Apple                    Apple iPhone 14 Pro Max     deep_purple
11            Vivo                                   Vivo Y21    diamond_glow
...            ...                                        ...             ...
4463         Mibro                     Mibro Lite Smart Watch           black
4464        Xiaomi                           Xiaomi Redmi 10A   chrome_silver
4465        Lenovo           Lenovo HE05 TWS Wireless Earbuds           black
4466         Digit                              Digit Glory 1           black
4467        Lenovo  Lenovo Livepods LP1 True Wireless Earbuds           white

       Product Memory  Product Value  ...          Courier  Tracking ID  \
0                   0          13999  ...              NaN          NaN
7     256gb - 8gb ram          69999  ...              NaN          NaN
8     128gb - 6gb ram          47199  ...              NaN          NaN
9               128gb         494999  ...              NaN          NaN
11     64gb - 4gb ram          42499  ...   selfpickup-lhe   selfpickup
...               ...            ...  ...              ...          ...
4463                0           8399  ...     priceoye-lhe      1000114
4464  128gb - 4gb ram          38999  ...  selfpickup-safa      1000222
4465                0           1499  ...              NaN          NaN
4466   32gb - 2gb ram          15299  ...              NaN          NaN
4467                0           2499  ...          leopard  ID196915105

                           Status         Status Date          Order Date  \
0             cancelled_abandoned 2023-01-01 11:36:58 2023-01-01 01:12:14
7             cancelled_abandoned 2023-01-02 12:34:19 2023-01-01 01:16:10
8             cancelled_abandoned 2023-01-02 12:34:17 2023-01-01 01:20:22
9             cancelled_abandoned 2023-01-01 14:48:45 2023-01-01 02:44:33
11                      delivered 2023-01-03 20:00:14 2023-01-01 04:39:43
...                           ...                 ...                 ...
4463                    delivered 2023-02-03 13:04:29 2023-01-31 23:20:33
4464                    delivered 2023-02-03 12:45:34 2023-01-31 23:23:40
4465  cancelled_mistakenly_placed 2023-02-02 16:18:20 2023-01-31 23:28:53
4466          cancelled_abandoned 2023-02-01 10:44:08 2023-01-31 23:30:35
4467                    delivered 2023-02-04 17:58:22 2023-01-31 23:34:27

     issued Coupon      Delivery Type  Direct Order Placed  \
0                -  standard_shipping                   No
7                -  standard_shipping                   No
8                -  standard_shipping                   No
9                -  standard_shipping                   No
11               -         selfpickup                   No
...            ...                ...                  ...
4463             -  standard_shipping                   No
4464             -         selfpickup                  Yes
4465             -  standard_shipping                   No
4466             -  standard_shipping                   No
4467             -  standard_shipping                   No

      Expected Delivery Date        Vendor Name
0                 2023-01-04                NaN
7                 2023-01-04                NaN
8                 2023-01-04                NaN
9                 2023-01-04                NaN
11                2023-01-03       Ideal Mobile
...                      ...                ...
4463              2023-02-02    Optus Solutions
4464              2023-02-02  Brother's Mobiles
4465              2023-02-02                NaN
4466              2023-02-03                NaN
4467              2023-02-03          Blue Tech

[2969 rows x 44 columns]